### ISSUE TITLE
Morning session code review

### ISSUE THREAD

**Issue by JohnFTitor** [gabyse1/repo-portfolio#18]
# Hi @gabyse1  👋🏻 #

You've done a great job so far with your Portfolio 💯 💯 

## To Highlight 🎉 

- ✅ Website Works correctly 
- ✅ You've used great logic to check if the email was lowercase using a regular expression which makes the code look cleaner

## Suggestions 🚀 ##

- [ ] Instead of using an already created span, you could create it dynamically with javascript

# Closing 😸 

Please let me know If you have any questions about my suggestions. We're all here to learn so let's take advantage of different perspectives!
Cheers and happy coding! 👨🏻‍💻 

<img src="https://media4.giphy.com/media/fT3PPZwB2lZMk/giphy.gif"/>

**Comment by gabyse1** [comment]
Thank you.
I am gonna create the span element dynamically.
